micronaut:
  application:
    name: dataMicronaut
mongodb:
  #uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:example}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test
netty:
  default:
    allocator:
      max-order: 3

